# Generated by Django 2.2.16 on 2020-12-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='contact',
        ),
    ]
