# Generated by Django 2.2.16 on 2020-12-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201227_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
