# Generated by Django 2.2.16 on 2021-01-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customertrasnscation_customer_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertrasnscation',
            name='bill',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
