# Generated by Django 2.2.17 on 2021-01-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customertrasnscationbill_customer'),
        ('core', '0007_customertrasnscation_bill'),
    ]

    operations = [
    ]
