# Generated by Django 2.2.17 on 2021-01-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210110_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerordereditems',
            name='product_detail',
        ),
        migrations.RemoveField(
            model_name='customertrasnscation',
            name='customer_detail',
        ),
    ]
