# Generated by Django 2.2.17 on 2021-01-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210111_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortrasnscation',
            name='bill',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
