# Generated by Django 2.2.17 on 2021-01-10 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210111_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendortrasnscationbill',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Vendor'),
        ),
    ]
