# Generated by Django 2.2.17 on 2021-01-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210111_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorordereditems',
            name='product_detail',
        ),
    ]
