# Generated by Django 2.2.16 on 2021-01-20 09:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_vendorordereditems_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.product_image_file_path),
        ),
    ]
