# Generated by Django 2.2.16 on 2021-01-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.PositiveIntegerField(),
        ),
    ]
