# Generated by Django 2.2.16 on 2021-02-15 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210213_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveproduct',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Warehouse'),
        ),
        migrations.AlterField(
            model_name='vendorordereditems',
            name='delivery_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Warehouse'),
        ),
    ]
